version: 2
ethernets:
  lo:
    match:
      name: lo
    addresses:
      - fc10::2/128
  enp1s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.5/24
      - fc00::5/64
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.2.1/24
      - fc02::1/64
    nameservers: {}
  enp3s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc04::2/64
    gateway6: fc04::1
    nameservers: {}
