version: 2
ethernets:
  lo:
    match:
      name: lo
    addresses:
      - fc14::1/64
  enp1s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.4/24
      - fc00::4/64
    gateway4: 192.168.100.1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc01::4/64
    nameservers: {}
  enp3s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.2.1/24
      - fc02::1/64
    nameservers: {}
