version: 2
ethernets:
  enp1s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.3/24
      - fc00::3/64
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.2.2/24
      - fc02::2/64
    gateway4: 192.168.2.1
    gateway6: fc02::1
    nameservers: {}
