version: 2
ethernets:
  enp1s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.3/24
      - fc00::3/64
    gateway4: 192.168.100.1
    gateway6: fc00::1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.3.2/24
      - fc03::2/64
    routes:
      - to: 192.168.2.0/24
        via: 192.168.3.1
      - to: fc02::/64
        via: fc03::1
    nameservers: {}
