version: 2
ethernets:
  enp1s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.2/24
      - fc00::2/64
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.1.2/24
      - fc01::2/64
    gateway4: 192.168.1.1
    gateway6: fc01::1
    nameservers: {}
