version: 2
ethernets:
  enp1s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.2/24
      - fc00::2/64
    gateway4: 192.168.100.1
    gateway6: fc00::1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.2.2/24
      - fc02::2/64
    routes:
      - to: 192.168.3.0/24
        via: 192.168.2.1
      - to: fc03::/64
        via: fc02::1
    nameservers: {}
